-- ============================================================================
-- AI Video Studio v2 — 种子数据（seed.sql）
--
-- 当前版本：空种子（无需落库的预设数据）。
--
-- 按必读文档核对后的结论：
--
-- 1. 平台预设模型配置（机制 B 平台预设适配器）
--    —— 不落库。预设清单定义在《05-模型接入清单.md》（provider 名、协议、
--       base_url、计量口径等），由后端 provider 适配层硬编码维护，经
--       GET /api/model-configs/presets（03-接口文档）按 provider_class
--       返回；users 的 model_configs 由用户「选预设 + 填 Key」后按行落库，
--       不存在需要预置到数据库的模板行。
--
-- 2. 系统内置 prompts（7 类模板）
--    —— 不落库。归属待评审：04-数据库文档 附录 A-3「系统内置 prompts 的
--       归属」——prompts.user_id 为 NOT NULL，系统默认模板需平台保留用户
--       （如 system@avs.internal）承载或放宽 user_id 可空，评审前不下种子。
--
-- 3. 平台 Key 池（platform_key_pool）
--    —— 不落库。平台托管 Key 属部署期秘密（environment 或外部 Secret
--       Manager），由运维在启动时经 credentials(owner_scope='platform')
--       登记，运行态再入池；不入种子文件，避免明文/密文 Key 进仓库。
--
-- 4. 体验积分（trial_credits=120）与订阅额度
--    —— 不落库。注册时由应用层在同一事务内创建 credit_accounts 并写
--       grant_trial 流水；积分/额度常量属业务代码配置（见 00-CONTRACT
--       C11 / C2），不在此预置。
--
-- 结论：本文件无 INSERT 语句，作为迁移体系的可选挂载点保留
-- （后续 A-3 评审通过或新增平台级配置表时在此追加）。
-- 执行方式：psql -f seed.sql 或由 migrate.js 之后手动执行（空文件恒成功）。
-- ============================================================================
