/**
 * L10 开放导出（api 本地打包 zip → MinIO + exports 表）（Phase 4，TS 移植 v2 steps/l10.js）。
 *
 * 打包内容：final.mp4 + subtitles.srt + script.md + storyboard.json + LICENSE.txt
 * 产物：MinIO tasks/<id>/export/project-export-YYYYMMDD.zip → exports 行
 *       （expires_at = now()+30 天，schema 默认）+ assets(type='zip')。
 * 幂等：同一 (task, zip 文件名) 已导出（exports 查 task_id）→ 直接复用。
 */

import archiver from 'archiver';
import * as lib from '../lib.js';
import type { StepRunnerInput } from '../queues.js';

const LICENSE_TEXT = `AI Video Studio 生成内容使用说明
=============================

1. 本视频由 AI Video Studio 自动生成（成片 + 字幕 + 文案 + 分镜表）。
2. 生成素材（图片/视频/音频）由所配置的 AI 供应商提供，其使用权利
   以供应商服务条款为准。
3. 文案与分镜结构为 AI 生成内容，引用或商用前请自行复核合规性
   （医疗/金融绝对化表述、名人背书暗示、版权文本等红线）。
4. 平台不对用户输入内容的合法性负责；导出即视为已阅读本说明。

Generated by AI Video Studio.
`;

function ymd(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}`;
}

function buildZip(entries: Array<{ name: string; buffer: Buffer }>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.on('data', (c) => chunks.push(c as Buffer));
    archive.on('error', reject);
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    for (const e of entries) {
      archive.append(e.buffer, { name: e.name });
    }
    archive.finalize();
  });
}

export const l10 = {
  async run(ctx: StepRunnerInput) {
    const { pg, minio, task } = ctx;
    const taskId = task.id;
    const zipName = `project-export-${ymd()}.zip`;
    const zipKey = `tasks/${taskId}/export/${zipName}`;

    // 幂等说明（2026-08-19 调整）：不再"已存在即复用"——素材/成片可能已被 rerun 更新，
    // 重新导出必须重新打包，保证 zip 永远是最新素材。INSERT 走 ON CONFLICT 更新同 key 行。
    const files: Array<{ name: string; buffer: Buffer }> = [];
    const missing: string[] = [];

    async function add(key: string | null, name: string, required: boolean): Promise<void> {
      if (!key) {
        if (required) missing.push(name);
        return;
      }
      try {
        const buf = await lib.downloadFromMinio(minio, key);
        if (buf && buf.length > 0) files.push({ name, buffer: buf });
        else if (required) missing.push(name);
      } catch {
        if (required) missing.push(name);
      }
    }

    await add(`tasks/${taskId}/final.mp4`, 'final.mp4', true);
    await add(`tasks/${taskId}/subtitles.srt`, 'subtitles.srt', false);
    await add(`tasks/${taskId}/script.md`, 'script.md', false);
    await add(`tasks/${taskId}/storyboard.json`, 'storyboard.json', false);

    // 素材打包：全部镜头图 + 配音 → assets/shots/、assets/audio/（缺失不阻塞导出）。
    // 用户反馈：导出应含完整素材，可再导入/本地复用（2026-08-19）。
    try {
      const { rows: assetRows } = await pg.query(
        `SELECT type, minio_key FROM assets
          WHERE task_id = $1 AND type IN ('shot', 'audio')
          ORDER BY minio_key`,
        [taskId],
      );
      for (const a of assetRows as Array<{ type: string; minio_key: string }>) {
        const key = String(a.minio_key);
        const base = String(key.split('/').pop() || key);
        const sub = a.type === 'shot' ? 'assets/shots' : 'assets/audio';
        const buf = await lib.downloadFromMinio(minio, key).catch(() => null);
        if (buf && buf.length > 0) files.push({ name: `${sub}/${base}`, buffer: buf });
      }
    } catch (err) {
      console.warn(`[l10] asset collection failed for ${taskId}: ${(err as Error).message}`);
    }

    if (files.length === 0) {
      throw new Error('导出失败：final.mp4 产物缺失');
    }
    files.push({ name: 'LICENSE.txt', buffer: Buffer.from(LICENSE_TEXT, 'utf8') });

    const zipBuf = await buildZip(files);
    const zipHash = lib.sha256hex(zipBuf);
    await lib.uploadToMinio(minio, zipKey, zipBuf, 'application/zip');

    const { rows } = await pg.query(
      `INSERT INTO exports (task_id, minio_key, zip_hash)
       VALUES ($1, $2, $3)
       ON CONFLICT (minio_key) DO UPDATE
         SET zip_hash = EXCLUDED.zip_hash, expires_at = now() + '30 days'::interval
       RETURNING id, minio_key, zip_hash, expires_at`,
      [taskId, zipKey, zipHash],
    );
    const row = rows[0] as { id: string; minio_key: string; zip_hash: string; expires_at: Date };

    await lib.insertAsset(pg, taskId, 'zip', zipKey, zipBuf.length);

    return {
      payload: {
        kind: 'export',
        export_id: row.id,
        zip_key: row.minio_key,
        zip_hash: row.zip_hash,
        size: zipBuf.length,
        expires_at: row.expires_at,
        missing_files: missing,
      },
    };
  },
};
